// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import java.util.HashMap;
import java.util.List;

import com.pathplanner.lib.PathConstraints;
import com.pathplanner.lib.PathPlanner;
import com.pathplanner.lib.PathPlannerTrajectory;
import com.pathplanner.lib.auto.PIDConstants;
import com.pathplanner.lib.auto.RamseteAutoBuilder;

import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.controller.RamseteController;
import edu.wpi.first.math.controller.SimpleMotorFeedforward;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.trajectory.Trajectory;
import edu.wpi.first.math.trajectory.TrajectoryConfig;
import edu.wpi.first.math.trajectory.TrajectoryGenerator;
import edu.wpi.first.math.trajectory.constraint.DifferentialDriveVoltageConstraint;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.RamseteCommand;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import edu.wpi.first.wpilibj2.command.CommandBase;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import frc.robot.subsystems.DriveTrain;
import frc.robot.Constants;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class AutonomousCommand extends CommandBase {

    DriveTrain m_drivetrain;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    public AutonomousCommand(DriveTrain drivetrain) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // m_subsystem = subsystem;
        // addRequirements(m_subsystem);    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    m_drivetrain = drivetrain;
    drivetrain.resetEncoders();

    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        Command m_autonomousCommand = getAutonomousCommandPath();

    // schedule the autonomous command (example)
    if (m_autonomousCommand != null) {
      m_autonomousCommand.schedule();
        }
    }

    public Command getAutonomousCommandPath() {
        

        // This will load the file "Example Path.path" and generate it with a max velocity of 4 m/s and a max acceleration of 3 m/s^2
    PathPlannerTrajectory examplePath = PathPlanner.loadPath("Reverse Waypoint", new PathConstraints(Constants.kMaxSpeedMetersPerSecond, Constants.kMaxAccelerationMetersPerSecondSquared));
    
    m_drivetrain.resetOdometry(examplePath.getInitialPose());

    HashMap<String, Command> eventMap = new HashMap<>();
    // Create the AutoBuilder. This only needs to be created once when robot code starts, not every time you want to create an auto command. A good place to put this is in RobotContainer along with your subsystems.
    RamseteAutoBuilder autoBuilder = new RamseteAutoBuilder(
        m_drivetrain::getPose,
        m_drivetrain::resetOdometry,
        new RamseteController(Constants.kRamseteB, Constants.kRamseteZeta),
        Constants.kDriveKinematics,
        new SimpleMotorFeedforward(
            Constants.ksVolts,
            Constants.kvVoltSecondsPerMeter,
            Constants.kaVoltSecondsSquaredPerMeter),
        m_drivetrain::getWheelSpeeds,
        new PIDConstants(Constants.kPDriveVel, Constants.kIDriveVel, Constants.kDDriveVel), //0.1714
        m_drivetrain::tankDriveVolts,
        eventMap,
        true,
        m_drivetrain
    );

    Command fullAuto = autoBuilder.fullAuto(examplePath);


    // Run path following command, then stop at the end.
    return new SequentialCommandGroup(
        fullAuto.andThen(() -> m_drivetrain.tankDriveVolts(0, 0)));
    }


    // public Command getAutonomousCommand() {
    //     // Create a voltage constraint to ensure we don't accelerate too fast

    // var autoVoltageConstraint =
    // new DifferentialDriveVoltageConstraint(
    //     new SimpleMotorFeedforward(
    //         Constants.ksVolts,
    //         Constants.kvVoltSecondsPerMeter,
    //         Constants.kaVoltSecondsSquaredPerMeter),
    //     Constants.kDriveKinematics,

    //     10);

    //      // Create config for trajectory

    // TrajectoryConfig config =
    // new TrajectoryConfig(
    //         Constants.kMaxSpeedMetersPerSecond,
    //         Constants.kMaxAccelerationMetersPerSecondSquared)
    //     // Add kinematics to ensure max speed is actually obeyed
    //     .setKinematics(Constants.kDriveKinematics)
    //     // Apply the voltage constraint
    //     .addConstraint(autoVoltageConstraint);

    //      // An example trajectory to follow.  All units in meters.

    // Trajectory exampleTrajectory =

    // TrajectoryGenerator.generateTrajectory(
    //     // Start at the origin facing the +X direction
    //     new Pose2d(0, 0, new Rotation2d(0)),
    //     // Pass through these two interior waypoints, making an 's' curve path
    //     List.of(/*new Translation2d(1, 1), new Translation2d(1, 0.5)*/),
    //     // End 3 meters straight ahead of where we started, facing forward
    //     new Pose2d(2, 1
    //     , new Rotation2d(Math.toRadians(0))),
    //     // Pass config
    //     config);

    // RamseteCommand ramseteCommand =
    // new RamseteCommand(
    //     exampleTrajectory,
    //     m_drivetrain::getPose,
    //     new RamseteController(Constants.kRamseteB, Constants.kRamseteZeta),
    //     new SimpleMotorFeedforward(
    //         Constants.ksVolts,
    //         Constants.kvVoltSecondsPerMeter,
    //         Constants.kaVoltSecondsSquaredPerMeter),
    //     Constants.kDriveKinematics,
    //     m_drivetrain::getWheelSpeeds,
    //     new PIDController(Constants.kPDriveVel, 1, 0), //0.1714
    //     // RamseteCommand passes volts to the callback
    //     new PIDController(Constants.kPDriveVel, 1, 0),
    //     m_drivetrain::tankDriveVolts,
    //     m_drivetrain);

    // // Run path following command, then stop at the end.
    // return new SequentialCommandGroup(
    //     new InstantCommand(() -> m_drivetrain.zeroHeading()), 
    //     new InstantCommand(() -> m_drivetrain.resetEncoders()), 
    //     new InstantCommand(() -> m_drivetrain.resetOdometry(exampleTrajectory.getInitialPose())), 
    //     ramseteCommand.andThen(() -> m_drivetrain.tankDriveVolts(0, 0)));
    // }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
