// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import java.util.HashMap;

import com.pathplanner.lib.PathConstraints;
import com.pathplanner.lib.PathPlanner;
import com.pathplanner.lib.PathPlannerTrajectory;
import com.pathplanner.lib.auto.PIDConstants;
import com.pathplanner.lib.auto.RamseteAutoBuilder;

import edu.wpi.first.math.controller.RamseteController;
import edu.wpi.first.math.controller.SimpleMotorFeedforward;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.DriveTrain;
import frc.robot.Constants;
import frc.robot.RobotContainer;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.DriveTrain;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class AutonomousCommand extends CommandBase {

    private Command m_autonomousCommand;

    private double ksVolts;
    private double kvVoltSecondsPerMeter;
    private double kaVoltSecondsSquaredPerMeter;
    private double kPDriveVel;
    private double kIDriveVel;
    private double kDDriveVel;
    private double kMaxSpeedMetersPerSecond;
    private double kMaxAccelerationMetersPerSecondSquared;
    private PathPlannerTrajectory traj;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private final DriveTrain m_driveTrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    public AutonomousCommand(DriveTrain subsystem) {

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_driveTrain = subsystem;
        this.traj = null;
        addRequirements(m_driveTrain);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        subsystem.resetEncoders();
    }
    public AutonomousCommand(DriveTrain subsystem, PathPlannerTrajectory traj) {

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_driveTrain = subsystem;
        this.traj = traj;
        addRequirements(m_driveTrain);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        subsystem.resetEncoders();
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        if (RobotContainer.getInstance().getSelectedPath() != "None") {
            m_autonomousCommand = getAutonomousCommandPath(traj);
        }

        // schedule the autonomous command (example)
        if (m_autonomousCommand != null) {
            m_autonomousCommand.schedule();
        }
    }
    public Command getAutonomousCommandPath(PathPlannerTrajectory trajectory) {
        getSmartDashValues();

        /**
         * This will load the file "Example Path.path" and generate it with a max
         * velocity of 4 m/s and a max acceleration of 3 m/s^2
         */
        PathPlannerTrajectory examplePath;
        if (traj == null) {
            examplePath = PathPlanner.loadPath(
                RobotContainer.getInstance().getSelectedPath(),
                new PathConstraints(kMaxSpeedMetersPerSecond,
                        kMaxAccelerationMetersPerSecondSquared));
        }
        else {
            examplePath = trajectory;
        }

        HashMap<String, Command> eventMap = new HashMap<>();

        /**
         * Create the AutoBuilder. This only needs to be created once when robot code
         * starts, not every time you want to create an auto command. A good place to
         * put this is in RobotContainer along with your subsystems.
         */
        RamseteAutoBuilder autoBuilder = new RamseteAutoBuilder(
                m_driveTrain::getPose,
                m_driveTrain::resetOdometry,
                new RamseteController(Constants.kRamseteB, Constants.kRamseteZeta),
                Constants.kDriveKinematics,
                new SimpleMotorFeedforward(
                        ksVolts,
                        kvVoltSecondsPerMeter,
                        kaVoltSecondsSquaredPerMeter),
                m_driveTrain::getWheelSpeeds,
                new PIDConstants(kPDriveVel, kIDriveVel, kDDriveVel),
                m_driveTrain::tankDriveVolts,
                eventMap,
                true,
                m_driveTrain);

        Command fullAuto = autoBuilder.fullAuto(examplePath);

        // Run path following command, then stop at the end.
        return new SequentialCommandGroup(
                fullAuto.andThen(() -> m_driveTrain.tankDriveVolts(0, 0)));
    }

    private void getSmartDashValues() {
        ksVolts = SmartDashboard.getNumber("ksVolts", Constants.ksVolts);
        kvVoltSecondsPerMeter = SmartDashboard.getNumber("kvVoltSecondsPerMeter", Constants.kvVoltSecondsPerMeter);
        kaVoltSecondsSquaredPerMeter = SmartDashboard.getNumber("kaVoltSecondsSquaredPerMeter",
                Constants.kaVoltSecondsSquaredPerMeter);
        kPDriveVel = SmartDashboard.getNumber("kPDriveVel", Constants.kPDriveVel);
        kIDriveVel = SmartDashboard.getNumber("kIDriveVel", Constants.kIDriveVel);
        kDDriveVel = SmartDashboard.getNumber("kDDriveVel", Constants.kDDriveVel);
        kMaxSpeedMetersPerSecond = SmartDashboard.getNumber("kMaxSpeedMetersPerSecond",
                Constants.kMaxSpeedMetersPerSecond);
        kMaxAccelerationMetersPerSecondSquared = SmartDashboard.getNumber("kMaxAccelerationMetersPerSecondSquared",
                Constants.kMaxAccelerationMetersPerSecondSquared);
    }
    
    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        if (m_autonomousCommand != null) {
            SmartDashboard.putBoolean("Path Running", m_autonomousCommand.isScheduled());
        }

    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
